In [462]:
#жмём не думая
import pandas as pd
import requests
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.select import Select
import time
import numpy as np

### SNGS

In [5]:
#вставляем ссылку с нужным инструментом и датой
url = 'https://www.moex.com/ru/marketdata/#/mode=instrument&secid=SNGS&boardgroupid=57&mode_type=history&date_from=2022-10-01&date_till=2023-05-01'

In [6]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [7]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [239]:
df = pd.DataFrame()

In [240]:
#читаем первую страницу
df = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]

In [241]:
#пишем сколько страниц всего
i = 8

In [242]:
c = 0
while c < i-1: 
    print(c)
    driver.find_element(By.XPATH, '//*[@id="instrument-table"]/div[1]/div[2]/div/div/div/button[9]/span').click()
    time.sleep(1)
    df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]
    df = df.append(df1)
    c += 1

0
1
2
3
4
5
6

In [243]:
df['Срвзв.цена'] = df['Срвзв.цена'].apply(lambda x: float(str(x)[:2] + '.' + str(x)[2:]))

In [244]:
df['Первая'] = df['Первая'].apply(lambda x: float(str(x)[:2] + '.' + str(x)[2:]))

In [245]:
df['Минимум'] = df['Минимум'].apply(lambda x: float(str(x)[:2] + '.' + str(x)[2:]))

In [246]:
df['Максимум'] = df['Максимум'].apply(lambda x: float(str(x)[:2] + '.' + str(x)[2:]))

In [247]:
df['Закрытия'] = df['Закрытия'].apply(lambda x: float(str(x)[:2] + '.' + str(x)[2:]))

In [248]:
df['Объем'] = df['Объем'].apply(lambda x: x.replace('\xa0', "").replace(',', '.'))

In [249]:
#df['Объем'] = df['Объем'].apply(lambda x: float(x))

In [250]:
df

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2023-04-28,SNGS,8223,362865375.5,25.210,25.56,24.910,25.600,25.210
1,2023-04-27,SNGS,10855,533600592,25.375,25.19,25.050,25.600,25.550
2,2023-04-26,SNGS,14144,693739655.5,25.295,25.44,24.830,25.595,25.235
3,2023-04-25,SNGS,16583,934038845.5,25.750,26.03,25.425,26.255,25.685
4,2023-04-24,SNGS,30820,1698111524.5,26.075,26.33,25.620,26.695,25.895
...,...,...,...,...,...,...,...,...,...
1,2022-10-07,SNGS,15165,380936162.5,18.055,18.50,17.515,18.520,17.820
2,2022-10-06,SNGS,12324,312821337,18.830,19.08,18.500,19.250,18.635
3,2022-10-05,SNGS,23658,826855754,18.750,18.86,18.070,19.565,18.890
4,2022-10-04,SNGS,16137,546577987,18.790,19.30,18.400,19.300,18.930
5,2022-10-03,SNGS,20840,609790826.5,18.480,18.20,17.850,19.180,18.800

In [251]:
df.to_csv('SNGS_okt-may.csv')

### SBER

In [418]:
#вставляем ссылку с нужным инструментом и датой
url = 'https://www.moex.com/ru/marketdata/#/mode=instrument&secid=SBER&boardgroupid=57&mode_type=history&date_from=2022-10-01&date_till=2023-05-01'

In [419]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [420]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [421]:
df = pd.DataFrame()

In [422]:
#читаем первую страницу
df = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]

In [423]:
#пишем сколько страниц всего
i = 8

In [424]:
c = 0
while c < i-1: 
    print(c)
    driver.find_element(By.XPATH, '//*[@id="instrument-table"]/div[1]/div[2]/div/div/div/button[9]/span').click()
    time.sleep(1)
    df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]
    df = df.append(df1)
    c += 1

0
1
2
3
4
5
6

In [425]:
df['Срвзв.цена'] = df['Срвзв.цена'].apply(lambda x: float(str(x)[:3] + '.' + str(x)[3:]))

In [426]:
df['Первая'] = df['Первая'].apply(lambda x: float(str(x)[:3] + '.' + str(x)[3:]))

In [427]:
df['Минимум'] = df['Минимум'].apply(lambda x: float(str(x)[:3] + '.' + str(x)[3:]))

In [428]:
df['Максимум'] = df['Максимум'].apply(lambda x: float(str(x)[:3] + '.' + str(x)[3:]))

In [429]:
df['Закрытия'] = df['Закрытия'].apply(lambda x: float(str(x)[:3] + '.' + str(x)[3:]))

In [430]:
df['Объем'] = df['Объем'].apply(lambda x: x.replace('\xa0', "").replace(',', '.'))

In [431]:
#df['Объем'] = df['Объем'].apply(lambda x: float(x))

In [432]:
df

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2023-04-28,SBER,95222,11892356487.7,239.85,240.90,237.66,241.58,240.41
1,2023-04-27,SBER,112733,16307607839.2,238.73,235.59,235.13,240.74,239.49
2,2023-04-26,SBER,50819,5751047264.4,235.41,235.60,234.91,235.95,235.33
3,2023-04-25,SBER,65347,7565048264.5,235.02,235.13,234.21,235.82,235.29
4,2023-04-24,SBER,68329,7185358111.2,235.30,235.07,234.10,236.40,235.14
...,...,...,...,...,...,...,...,...,...
1,2022-10-07,SBER,176627,9560941533.5,105.08,107.70,101.30,108.48,103.83
2,2022-10-06,SBER,98405,5630301035.4,108.81,108.65,107.57,110.38,108.55
3,2022-10-05,SBER,150329,9776634296.1,108.13,110.49,106.25,110.49,109.00
4,2022-10-04,SBER,132828,9371218814.4,112.14,115.06,110.30,115.50,111.26
5,2022-10-03,SBER,149577,8280923624.7,111.96,110.62,109.00,114.65,114.03

In [433]:
df.to_csv('SBER_okt-may.csv')

### Si

In [375]:
#вставляем ссылку с нужным инструментом
url = 'https://www.moex.com/ru/forts/contractbaseresults.aspx?base=Si'  #настроим вручную дату

In [376]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [377]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [378]:
df = pd.DataFrame()

In [379]:
#не читаем всё разом, потому что возникает ошибка если выбрать нужным нам период полностью

In [380]:
#читаем с 1 января по 1 мая
df = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [381]:
df = df[0:82]

In [383]:
#читаем с 1 октября по 31 декабря
df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [384]:
df1 = df1[0:82]

In [385]:
df = df1.append(df)

In [386]:
df.columns

MultiIndex([(                        'Дата',                         'Дата'),
            (                 'Кодфьючерса',                  'Кодфьючерса'),
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            (                   'Изменение',                    'Изменение'),
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')],
           )

In [393]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: (str(x).replace('\xa0', "")))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [394]:
#чтобы ошибка не вылезала
def tryy(y):
    try:
        y = float(y)
        return(y)
    except:  
        return(y)

In [395]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: tryy(x))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [397]:
df.to_csv('Si_okt-may.csv')

### OG

In [398]:
#вставляем ссылку с нужным инструментом
url = 'https://www.moex.com/ru/forts/contractbaseresults.aspx?base=OG'  #настроим вручную дату

In [399]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [400]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [401]:
df = pd.DataFrame()

In [402]:
#не читаем всё разом, потому что возникает ошибка если выбрать нужным нам период полностью

In [403]:
#читаем с 1 января по 1 мая
df = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [404]:
df = df[0:82]

In [405]:
#читаем с 1 октября по 31 декабря
df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [406]:
df1 = df1[0:82]

In [407]:
df = df1.append(df)

In [409]:
df.columns

MultiIndex([(                        'Дата',                         'Дата'),
            (                 'Кодфьючерса',                  'Кодфьючерса'),
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            (                   'Изменение',                    'Изменение'),
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')],
           )

In [410]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: (str(x).replace('\xa0', "")))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [411]:
#чтобы ошибка не вылезала
def tryy(y):
    try:
        y = float(y)
        return(y)
    except:  
        return(y)

In [412]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
           
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: tryy(x))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [414]:
df.to_csv('OG_okt-may.csv')

### Причешем таблицы

In [717]:
SNGS = pd.read_csv('SNGS_okt-may.csv')

In [718]:
SNGS = SNGS[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем',
       'Срвзв.цена', 'Первая', 'Минимум', 'Максимум', 'Закрытия']]

In [719]:
SNGS['Дата торгов'] = pd.to_datetime(SNGS['Дата торгов'], yearfirst = True)

In [720]:
SNGS = SNGS.sort_values('Дата торгов')

In [721]:
SNGS.index = np.arange(0, len(SNGS))

In [722]:
SNGS

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2022-10-03,SNGS,20840,6.097908e+08,18.480,18.20,17.850,19.180,18.800
1,2022-10-04,SNGS,16137,5.465780e+08,18.790,19.30,18.400,19.300,18.930
2,2022-10-05,SNGS,23658,8.268558e+08,18.750,18.86,18.070,19.565,18.890
3,2022-10-06,SNGS,12324,3.128213e+08,18.830,19.08,18.500,19.250,18.635
4,2022-10-07,SNGS,15165,3.809362e+08,18.055,18.50,17.515,18.520,17.820
...,...,...,...,...,...,...,...,...,...
141,2023-04-24,SNGS,30820,1.698112e+09,26.075,26.33,25.620,26.695,25.895
142,2023-04-25,SNGS,16583,9.340388e+08,25.750,26.03,25.425,26.255,25.685
143,2023-04-26,SNGS,14144,6.937397e+08,25.295,25.44,24.830,25.595,25.235
144,2023-04-27,SNGS,10855,5.336006e+08,25.375,25.19,25.050,25.600,25.550
145,2023-04-28,SNGS,8223,3.628654e+08,25.210,25.56,24.910,25.600,25.210

In [723]:
SBER = pd.read_csv('SBER_okt-may.csv')

In [724]:
SBER = SBER[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем',
       'Срвзв.цена', 'Первая', 'Минимум', 'Максимум', 'Закрытия']]

In [725]:
SBER['Дата торгов'] = pd.to_datetime(SBER['Дата торгов'], yearfirst = True)

In [726]:
SBER = SBER.sort_values('Дата торгов')

In [727]:
SBER.index = np.arange(0, len(SBER))

In [728]:
SBER

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2022-10-03,SBER,149577,8.280924e+09,111.96,110.62,109.00,114.65,114.03
1,2022-10-04,SBER,132828,9.371219e+09,112.14,115.06,110.30,115.50,111.26
2,2022-10-05,SBER,150329,9.776634e+09,108.13,110.49,106.25,110.49,109.00
3,2022-10-06,SBER,98405,5.630301e+09,108.81,108.65,107.57,110.38,108.55
4,2022-10-07,SBER,176627,9.560942e+09,105.08,107.70,101.30,108.48,103.83
...,...,...,...,...,...,...,...,...,...
141,2023-04-24,SBER,68329,7.185358e+09,235.30,235.07,234.10,236.40,235.14
142,2023-04-25,SBER,65347,7.565048e+09,235.02,235.13,234.21,235.82,235.29
143,2023-04-26,SBER,50819,5.751047e+09,235.41,235.60,234.91,235.95,235.33
144,2023-04-27,SBER,112733,1.630761e+10,238.73,235.59,235.13,240.74,239.49
145,2023-04-28,SBER,95222,1.189236e+10,239.85,240.90,237.66,241.58,240.41

In [729]:
Si = pd.read_csv('Si_okt-may.csv')

In [730]:
Si = Si[['Дата', 'Кодфьючерса', 'Средне-взвешеннаяцена за лот',
       'Расчетнаяцена', 'Ценапервойсделки', 'Максим.цена', 'Миним.цена',
       'Ценапоследнейсделки', 'Изменение', 'Объемпоследнейсделки,контр.',
       'Числосделок', 'Объем торгов', 'Объем торгов.1',
       'Объем открытыхпозиций', 'Объем открытыхпозиций.1',
       'РазмерыГО(руб./контракт)']]

In [731]:
Si = Si[1::]

In [732]:
Si.index = np.arange(0, len(Si))

In [733]:
Si = Si.loc[(Si.index < 65) | (Si.index > 66)]

In [734]:
Si.index = np.arange(0, len(Si))

In [735]:
Si['Дата'] = pd.to_datetime(Si['Дата'], dayfirst = True)

In [736]:
Si = Si.sort_values('Дата')

In [737]:
Si = Si[:-1]

In [738]:
Si.index = np.arange(0, len(Si))

In [739]:
Si

,Дата,Кодфьючерса,Средне-взвешеннаяцена за лот,Расчетнаяцена,Ценапервойсделки,Максим.цена,Миним.цена,Ценапоследнейсделки,Изменение,"Объемпоследнейсделки,контр.",Числосделок,Объем торгов,Объем торгов.1,Объем открытыхпозиций,Объем открытыхпозиций.1,РазмерыГО(руб./контракт)
0,2022-10-03,SiZ2,57876.0,58172.0,58398.0,59280.0,56865.0,58147.0,"-0,36 %",3.0,651422.0,118703131215.0,2050990.0,368860740608.0,6340864.0,9359.0
1,2022-10-04,SiZ2,58227.0,57802.0,58179.0,58942.0,57543.0,57800.0,"-0,60 %",1.0,465209.0,82947201293.0,1424556.0,367415638504.0,6356452.0,9304.0
2,2022-10-05,SiZ2,58968.0,59744.0,57884.0,60160.0,57220.0,59777.0,"+3,42 %",10.0,556739.0,100343323478.0,1701652.0,376773026752.0,6306458.0,9561.0
3,2022-10-06,SiZ2,59710.0,59800.0,59790.0,60360.0,59111.0,59800.0,"+0,04 %",16.0,424645.0,78057391938.0,1307265.0,376656040800.0,6298596.0,9672.0
4,2022-10-07,SiZ2,60093.0,58608.0,59779.0,60995.0,58545.0,58598.0,"-2,01 %",33.0,536925.0,114752396811.0,1909587.0,369221491584.0,6299848.0,9662.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,2023-04-24,SiM3,80303.0,80339.0,80709.0,80747.0,79937.0,80320.0,"-0,42 %",1.0,175944.0,65501292454.0,815677.0,298791345748.0,3719132.0,12843.0
142,2023-04-25,SiM3,80570.0,80414.0,80369.0,80970.0,80111.0,80422.0,"+0,13 %",29.0,186775.0,81685796312.0,1013853.0,318458739360.0,3960240.0,12880.0
143,2023-04-26,SiM3,80604.0,80734.0,80398.0,80870.0,80243.0,80739.0,"+0,39 %",1.0,172507.0,53463131204.0,663281.0,319420518704.0,3956456.0,12881.0
144,2023-04-27,SiM3,80554.0,80370.0,80704.0,81175.0,80065.0,80341.0,"-0,49 %",3.0,192273.0,67058572742.0,832472.0,319088510280.0,3970244.0,12826.0
145,2023-04-28,SiM3,79299.0,79372.0,80339.0,80676.0,78250.0,79380.0,"-1,20 %",2.0,366794.0,141069059405.0,1778940.0,326012076568.0,4107394.0,12639.0

In [740]:
OG = pd.read_csv('OG_okt-may.csv')

In [741]:
OG = OG[['Дата', 'Кодфьючерса', 'Средне-взвешеннаяцена за лот',
       'Расчетнаяцена', 'Ценапервойсделки', 'Максим.цена', 'Миним.цена',
       'Ценапоследнейсделки', 'Изменение', 'Объемпоследнейсделки,контр.',
       'Числосделок', 'Объем торгов', 'Объем торгов.1',
       'Объем открытыхпозиций', 'Объем открытыхпозиций.1',
       'РазмерыГО(руб./контракт)']]

In [742]:
OG = OG[1::]

In [743]:
OG.index = np.arange(0, len(OG))

In [744]:
OG = OG.loc[(OG.index < 65) | (OG.index > 66)]

In [745]:
OG.index = np.arange(0, len(OG))

In [746]:
OG['Дата'] = pd.to_datetime(OG['Дата'], dayfirst = True)

In [747]:
OG = OG.sort_values('Дата')

In [748]:
OG = OG[:-1]

In [749]:
OG.index = np.arange(0, len(OG))

In [750]:
OG

,Дата,Кодфьючерса,Средне-взвешеннаяцена за лот,Расчетнаяцена,Ценапервойсделки,Максим.цена,Миним.цена,Ценапоследнейсделки,Изменение,"Объемпоследнейсделки,контр.",Числосделок,Объем торгов,Объем торгов.1,Объем открытыхпозиций,Объем открытыхпозиций.1,РазмерыГО(руб./контракт)
0,2022-10-03,OGZ2,5648.0,5554.0,5648.0,5648.0,5648.0,5648.0,"+8,70 %",1.0,1,5648.0,1.0,488752.0,88.0,1498.0
1,2022-10-04,OGZ2,5365.0,5365.0,5365.0,5365.0,5365.0,5365.0,"-5,01 %",1.0,2,10730.0,2.0,450660.0,84.0,1446.0
2,2022-10-05,OGZ2,-,5365.0,-,-,-,-,-,-,-,-,-,450660.0,84.0,1445.0
3,2022-10-06,OGZ2,-,5367.0,-,-,-,-,-,-,-,-,-,450828.0,84.0,1445.0
4,2022-10-07,OGZ2,5434.0,5300.0,5744.0,5746.0,5191.0,5191.0,-,1.0,5,27172.0,5.0,434600.0,82.0,1424.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,2023-04-24,OGM3,6800.0,6850.0,6751.0,6997.0,6750.0,6997.0,"+3,66 %",1.0,4,34000.0,5.0,739800.0,108.0,1473.0
142,2023-04-25,OGM3,-,6850.0,-,-,-,-,-,-,-,-,-,739800.0,108.0,1472.0
143,2023-04-26,OGM3,6668.0,6850.0,7194.0,7194.0,6600.0,6600.0,-,1.0,9,66679.0,10.0,671300.0,98.0,1470.0
144,2023-04-27,OGM3,6804.0,6662.0,6797.0,7050.0,6604.0,6650.0,"+0,76 %",1.0,16,115666.0,17.0,612904.0,92.0,1429.0
145,2023-04-28,OGM3,7031.0,6774.0,7165.0,7194.0,6711.0,7194.0,"+8,18 %",1.0,8,63277.0,9.0,636756.0,94.0,1446.0

In [751]:
SNGS.to_csv('SNGS_okt-may_v2.csv')

In [752]:
SBER.to_csv('SBER_okt-may_v2.csv')

In [753]:
Si.to_csv('Si_okt-may_v2.csv')

In [754]:
OG.to_csv('OG_okt-may_v2.csv')