In [2]:
#жмём не думая
import pandas as pd
import requests
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.select import Select
import time
import numpy as np
from tqdm import tqdm

### SNGS

In [11]:
#вставляем ссылку с нужным инструментом и датой
url = 'https://www.moex.com/ru/marketdata/#/mode=instrument&secid=SNGS&boardgroupid=57&mode_type=history&date_from=2022-10-01&date_till=2023-05-01'

In [12]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [13]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [43]:
df = pd.DataFrame()

In [44]:
#читаем первую страницу
df = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]

In [45]:
#пишем сколько страниц всего
i = 102

In [46]:
c = 0
while c < i-1: 
    print(c)
    driver.find_element(By.XPATH, '//*[@id="instrument-table"]/div[1]/div[2]/div/div/div/button[9]/span').click()
    time.sleep(3)
    df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]
    df = df.append(df1)
    c += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [47]:
df #не прочитались запятые почему-то, ниже исправим проблему

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2023-05-31,SNGS,5948,"267 791 369,5",2435,2415,24055,24505,2445
1,2023-05-30,SNGS,11787,431 421 745,24475,2451,241,24795,242
2,2023-05-29,SNGS,10700,"456 050 798,5",246,2449,2431,2482,24775
3,2023-05-26,SNGS,8406,311 175 353,24275,2416,2406,245,24365
4,2023-05-25,SNGS,6651,303 947 047,242,2431,24005,24375,241
...,...,...,...,...,...,...,...,...,...
16,2015-06-05,SNGS,10493,"420 405 100,5",31745,319,315,31995,319
17,2015-06-04,SNGS,15270,"576 908 949,5",3177,315,31415,3205,31965
18,2015-06-03,SNGS,17968,773 459 826,31685,31875,3108,32125,31505
19,2015-06-02,SNGS,10080,"658 378 287,5",31925,3208,312,3249,319
0,2015-06-01,SNGS,11065,"704 175 802,5",32185,3146,31415,3263,31885

In [66]:
def tryconvert(x): #чтобы пропускать ошибки
    try:
        y = float(str(x)[:2] + '.' + str(x)[2:])
        return y
    except:
        pass

In [49]:
df['Срвзв.цена'] = df['Срвзв.цена'].apply(lambda x: tryconvert(x))

In [50]:
df['Первая'] = df['Первая'].apply(lambda x: tryconvert(x))

In [51]:
df['Минимум'] = df['Минимум'].apply(lambda x: tryconvert(x))

In [52]:
df['Максимум'] = df['Максимум'].apply(lambda x: tryconvert(x))

In [53]:
df['Закрытия'] = df['Закрытия'].apply(lambda x: tryconvert(x))

In [54]:
df['Объем'] = df['Объем'].apply(lambda x: x.replace('\xa0', "").replace(',', '.'))

In [67]:
def vol(x):
    try:
        return(float(x))
    except:
        pass

In [56]:
df['Объем'] = df['Объем'].apply(lambda x: vol(x))

In [57]:
df = df[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем', 'Срвзв.цена']]

In [60]:
df.to_csv('SNGS_2015_2023.csv')

### SBER

In [239]:
#вставляем ссылку с нужным инструментом и датой
url = 'https://www.moex.com/ru/marketdata/#/mode=instrument&secid=SBER&boardgroupid=57&mode_type=history&date_from=2022-10-01&date_till=2023-05-01'

In [240]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [241]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [269]:
df = pd.DataFrame()

In [270]:
#читаем первую страницу
df = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]

In [271]:
#пишем сколько страниц всего
i = 102

In [272]:
c = 0
while c < i-1: 
    print(c)
    driver.find_element(By.XPATH, '//*[@id="instrument-table"]/div[1]/div[2]/div/div/div/button[9]/span').click()
    time.sleep(3)
    df1 = pd.read_html(driver.find_element(By.CLASS_NAME, "ui-table").get_attribute('outerHTML'))[0]
    df = df.append(df1)
    c += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [274]:
df #не прочитались запятые, ниже исправим проблему

,Дата торгов,Код инструмента,"Сделок, шт.",Объем,Срвзв.цена,Первая,Минимум,Максимум,Закрытия
0,2023-05-31,SBER,180151,"17 794 062 792,6",24405,244,24027,24718,24591
1,2023-05-30,SBER,153572,"20 681 901 312,6",24759,24884,2438,25085,24519
2,2023-05-29,SBER,133878,"17 017 721 478,8",25027,24978,24885,25259,25259
3,2023-05-26,SBER,150126,"17 064 289 810,3",24658,24345,24281,24964,24837
4,2023-05-25,SBER,152798,"17 342 598 158,4",24466,2461,24265,2474,24485
...,...,...,...,...,...,...,...,...,...
16,2015-06-05,SBER,79355,"5 480 891 746,2",7092,712,702,7175,7061
17,2015-06-04,SBER,106164,"7 845 641 687,8",7134,7169,7055,722,7125
18,2015-06-03,SBER,96899,"7 798 511 159,9",7274,7419,716,7435,7172
19,2015-06-02,SBER,66811,"5 525 454 638,9",7329,7288,7225,7425,7392
0,2015-06-01,SBER,93551,"8 321 019 554,8",735,737,7265,7449,7265

In [68]:
def tryconvert2(x): #чтобы пропускать ошибки
    try:
        y = float(str(x)[:3] + '.' + str(x)[3:])
        return y
    except:
        pass

In [276]:
df['Срвзв.цена'][0:1820] = df['Срвзв.цена'][0:1820].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/2978197830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][0:1820] = df['Срвзв.цена'][0:1820].apply(lambda x: tryconvert2(x))

In [279]:
df['Срвзв.цена'][1820:1839] = df['Срвзв.цена'][1820:1839].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/1742178481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1820:1839] = df['Срвзв.цена'][1820:1839].apply(lambda x: tryconvert2(x))

In [280]:
df['Срвзв.цена'][1839:1840] = df['Срвзв.цена'][1839:1840].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/3229537438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1839:1840] = df['Срвзв.цена'][1839:1840].apply(lambda x: tryconvert(x))

In [281]:
df['Срвзв.цена'][1840:1841] = df['Срвзв.цена'][1840:1841].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/2958353614.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1840:1841] = df['Срвзв.цена'][1840:1841].apply(lambda x: tryconvert(x))

In [282]:
df['Срвзв.цена'][1841:1870] = df['Срвзв.цена'][1841:1870].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/2332184919.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1841:1870] = df['Срвзв.цена'][1841:1870].apply(lambda x: tryconvert(x))

In [283]:
df['Срвзв.цена'][1870:1876] = df['Срвзв.цена'][1870:1876].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/3179352303.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1870:1876] = df['Срвзв.цена'][1870:1876].apply(lambda x: tryconvert2(x))

In [284]:
df['Срвзв.цена'][1876:1878] = df['Срвзв.цена'][1876:1878].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/2527677695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1876:1878] = df['Срвзв.цена'][1876:1878].apply(lambda x: tryconvert(x))

In [285]:
df['Срвзв.цена'][1878:1880] = df['Срвзв.цена'][1878:1880].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/2071575724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1878:1880] = df['Срвзв.цена'][1878:1880].apply(lambda x: tryconvert2(x))

In [286]:
df['Срвзв.цена'][1880:1881] = df['Срвзв.цена'][1880:1881].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/1424138043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1880:1881] = df['Срвзв.цена'][1880:1881].apply(lambda x: tryconvert2(x))

In [287]:
df['Срвзв.цена'][1881:1884] = df['Срвзв.цена'][1881:1884].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/1134157419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1881:1884] = df['Срвзв.цена'][1881:1884].apply(lambda x: tryconvert(x))

In [288]:
df['Срвзв.цена'][1884:1885] = df['Срвзв.цена'][1884:1885].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/1987557660.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1884:1885] = df['Срвзв.цена'][1884:1885].apply(lambda x: tryconvert2(x))

In [289]:
df['Срвзв.цена'][1885:1887] = df['Срвзв.цена'][1885:1887].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/4003531448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1885:1887] = df['Срвзв.цена'][1885:1887].apply(lambda x: tryconvert(x))

In [290]:
df['Срвзв.цена'][1887:1901] = df['Срвзв.цена'][1887:1901].apply(lambda x: tryconvert2(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/173384363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1887:1901] = df['Срвзв.цена'][1887:1901].apply(lambda x: tryconvert2(x))

In [291]:
df['Срвзв.цена'][1901:] = df['Срвзв.цена'][1901:].apply(lambda x: tryconvert(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/3623557267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Срвзв.цена'][1901:] = df['Срвзв.цена'][1901:].apply(lambda x: tryconvert(x))

In [292]:
df = df[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем', 'Срвзв.цена']]

In [297]:
df['Объем'] = df['Объем'].apply(lambda x: x.replace('\xa0', "").replace(',', '.'))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/59496852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Объем'] = df['Объем'].apply(lambda x: x.replace('\xa0', "").replace(',', '.'))

In [298]:
df['Объем'] = df['Объем'].apply(lambda x: vol(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_13780/1126344437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Объем'] = df['Объем'].apply(lambda x: vol(x))

In [299]:
df

   Дата торгов Код инструмента  Сделок, шт.         Объем Срвзв.цена
0   2023-05-31            SBER       180151  1.779406e+10     244.05
1   2023-05-30            SBER       153572  2.068190e+10     247.59
2   2023-05-29            SBER       133878  1.701772e+10     250.27
3   2023-05-26            SBER       150126  1.706429e+10     246.58
4   2023-05-25            SBER       152798  1.734260e+10     244.66
..         ...             ...          ...           ...        ...
16  2015-06-05            SBER        79355  5.480892e+09      70.92
17  2015-06-04            SBER       106164  7.845642e+09      71.34
18  2015-06-03            SBER        96899  7.798511e+09      72.74
19  2015-06-02            SBER        66811  5.525455e+09      73.29
0   2015-06-01            SBER        93551  8.321020e+09       73.5

[2021 rows x 5 columns]

In [300]:
df.to_csv('SBER_2015_2023.csv')

### Si

In [198]:
#вставляем ссылку с нужным инструментом
url = 'https://www.moex.com/ru/forts/contractbaseresults.aspx?base=Si'  #настроим вручную дату

In [199]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [200]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [201]:
df = pd.DataFrame()

In [202]:
#читаем 
df = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [203]:
df

            Дата  Кодфьючерса  Средне-взвешеннаяцена за лот  Расчетнаяцена  \
            Дата  Кодфьючерса  Средне-взвешеннаяцена за лот  Расчетнаяцена
0     01.06.2015         SiM5                        53 358         53 749
1     02.06.2015         SiM5                        53 527         53 400
2     03.06.2015         SiM5                        53 795         54 432
3     04.06.2015         SiM5                        55 353         56 199
4     05.06.2015         SiM5                        56 478         56 508
...          ...          ...                           ...            ...
2019  30.05.2023         SiM3                        80 730         81 072
2020  31.05.2023         SiM3                        80 945         81 019
2021         NaN          NaN                           NaN            NaN
2022        Дата  Кодфьючерса  Средне-взвешеннаяцена за лот  Расчетнаяцена
2023        Дата  Кодфьючерса  Средне-взвешеннаяцена за лот  Расчетнаяцена

      Ценапервойсделки  Максим.цена  Миним.цена  Ценапоследнейсделки  \
      Ценапервойсделки  Максим.цена  Миним.цена  Ценапоследнейсделки
0               52 650       53 814      52 561               53 749
1               53 725       54 009      53 226               53 400
2               53 340       54 628      52 935               54 432
3               54 406       56 297      54 363               56 199
4               56 235       57 390      55 707               56 508
...                ...          ...         ...                  ...
2019            80 800       81 323      80 088               81 050
2020            81 062       81 183      80 610               81 039
2021               NaN          NaN         NaN                  NaN
2022  Ценапервойсделки  Максим.цена  Миним.цена  Ценапоследнейсделки
2023  Ценапервойсделки  Максим.цена  Миним.цена  Ценапоследнейсделки

      Изменение  Объемпоследнейсделки,контр.  Числосделок     Объем торгов  \
      Изменение  Объемпоследнейсделки,контр.  Числосделок             руб.
0       +2,21 %                            1      561 640  158 339 141 109
1       -0,65 %                            3      569 499  148 111 977 125
2       +1,93 %                            1      687 524  195 232 865 779
3       +3,25 %                            1      744 915  214 637 486 533
4       +0,55 %                            5    1 088 592  277 975 818 931
...         ...                          ...          ...              ...
2019    +0,29 %                            4      248 338   85 953 509 197
2020    -0,01 %                            1      231 856   79 725 726 278
2021        NaN                          NaN          NaN              NaN
2022  Изменение  Объемпоследнейсделки,контр.  Числосделок     Объем торгов
2023  Изменение  Объемпоследнейсделки,контр.  Числосделок             руб.

                    Объем открытыхпозиций                         \
            контр.                   руб.                 контр.
0        2 967 867        116 583 193 470              2 169 030
1        2 767 018        103 894 826 400              1 945 596
2        3 629 234        115 987 080 384              2 130 862
3        3 877 042        119 945 525 700              2 134 300
4        4 921 872        112 609 820 496              1 992 812
...            ...                    ...                    ...
2019     1 064 698        313 666 757 280              3 868 990
2020       984 898        301 662 093 650              3 723 350
2021           NaN                    NaN                    NaN
2022  Объем торгов  Объем открытыхпозиций  Объем открытыхпозиций
2023        контр.                   руб.                 контр.

      РазмерыГО(руб./контракт)
      РазмерыГО(руб./контракт)
0                        5 914
1                        5 874
2                        5 988
3                        6 182
4                        5 086
...                        ...
2019                    12 402
2020                    12 380
2021                       NaN
2022  РазмерыГО(руб./контракт)
2023  РазмерыГО(руб./контракт)

[2024 rows x 16 columns]

In [204]:
df.columns

MultiIndex([(                        'Дата',                         'Дата'),
            (                 'Кодфьючерса',                  'Кодфьючерса'),
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            (                   'Изменение',                    'Изменение'),
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')],
           )

In [205]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: (str(x).replace('\xa0', "")))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [206]:
#чтобы ошибка не вылезала
def tryy(y):
    try:
        y = float(y)
        return(y)
    except:  
        pass

In [207]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: tryy(x))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [211]:
df = df[:2021]

In [212]:
df

            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена  \
            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена
0     01.06.2015        SiM5                      53358.0       53749.0
1     02.06.2015        SiM5                      53527.0       53400.0
2     03.06.2015        SiM5                      53795.0       54432.0
3     04.06.2015        SiM5                      55353.0       56199.0
4     05.06.2015        SiM5                      56478.0       56508.0
...          ...         ...                          ...           ...
2016  25.05.2023        SiM3                      79906.0       80120.0
2017  26.05.2023        SiM3                      79889.0       79974.0
2018  29.05.2023        SiM3                      80255.0       80800.0
2019  30.05.2023        SiM3                      80730.0       81072.0
2020  31.05.2023        SiM3                      80945.0       81019.0

     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение  \
     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение
0             52650.0     53814.0    52561.0             53749.0   +2,21 %
1             53725.0     54009.0    53226.0             53400.0   -0,65 %
2             53340.0     54628.0    52935.0             54432.0   +1,93 %
3             54406.0     56297.0    54363.0             56199.0   +3,25 %
4             56235.0     57390.0    55707.0             56508.0   +0,55 %
...               ...         ...        ...                 ...       ...
2016          80027.0     80250.0    79512.0             80101.0   +0,18 %
2017          80100.0     80170.0    79581.0             79956.0   -0,18 %
2018          79933.0     80932.0    79731.0             80815.0   +1,07 %
2019          80800.0     81323.0    80088.0             81050.0   +0,29 %
2020          81062.0     81183.0    80610.0             81039.0   -0,01 %

     Объемпоследнейсделки,контр. Числосделок  Объем торгов             \
     Объемпоследнейсделки,контр. Числосделок          руб.     контр.
0                            1.0    561640.0  1.583391e+11  2967867.0
1                            3.0    569499.0  1.481120e+11  2767018.0
2                            1.0    687524.0  1.952329e+11  3629234.0
3                            1.0    744915.0  2.146375e+11  3877042.0
4                            5.0   1088592.0  2.779758e+11  4921872.0
...                          ...         ...           ...        ...
2016                         4.0    223027.0  6.962116e+10   871289.0
2017                         2.0    179239.0  5.412557e+10   677495.0
2018                        10.0    249892.0  8.655212e+10  1078487.0
2019                         4.0    248338.0  8.595351e+10  1064698.0
2020                         1.0    231856.0  7.972573e+10   984898.0

     Объем открытыхпозиций            РазмерыГО(руб./контракт)
                      руб.     контр. РазмерыГО(руб./контракт)
0             1.165832e+11  2169030.0                   5914.0
1             1.038948e+11  1945596.0                   5874.0
2             1.159871e+11  2130862.0                   5988.0
3             1.199455e+11  2134300.0                   6182.0
4             1.126098e+11  1992812.0                   5086.0
...                    ...        ...                      ...
2016          3.213248e+11  4010544.0                  12339.0
2017          3.192193e+11  3991538.0                  12261.0
2018          3.173176e+11  3927198.0                  12377.0
2019          3.136668e+11  3868990.0                  12402.0
2020          3.016621e+11  3723350.0                  12380.0

[2021 rows x 16 columns]

In [216]:
df = df.iloc[::-1]

In [218]:
df.reindex(index=df.index[::-1])

            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена  \
            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена
0     01.06.2015        SiM5                      53358.0       53749.0
1     02.06.2015        SiM5                      53527.0       53400.0
2     03.06.2015        SiM5                      53795.0       54432.0
3     04.06.2015        SiM5                      55353.0       56199.0
4     05.06.2015        SiM5                      56478.0       56508.0
...          ...         ...                          ...           ...
2016  25.05.2023        SiM3                      79906.0       80120.0
2017  26.05.2023        SiM3                      79889.0       79974.0
2018  29.05.2023        SiM3                      80255.0       80800.0
2019  30.05.2023        SiM3                      80730.0       81072.0
2020  31.05.2023        SiM3                      80945.0       81019.0

     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение  \
     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение
0             52650.0     53814.0    52561.0             53749.0   +2,21 %
1             53725.0     54009.0    53226.0             53400.0   -0,65 %
2             53340.0     54628.0    52935.0             54432.0   +1,93 %
3             54406.0     56297.0    54363.0             56199.0   +3,25 %
4             56235.0     57390.0    55707.0             56508.0   +0,55 %
...               ...         ...        ...                 ...       ...
2016          80027.0     80250.0    79512.0             80101.0   +0,18 %
2017          80100.0     80170.0    79581.0             79956.0   -0,18 %
2018          79933.0     80932.0    79731.0             80815.0   +1,07 %
2019          80800.0     81323.0    80088.0             81050.0   +0,29 %
2020          81062.0     81183.0    80610.0             81039.0   -0,01 %

     Объемпоследнейсделки,контр. Числосделок  Объем торгов             \
     Объемпоследнейсделки,контр. Числосделок          руб.     контр.
0                            1.0    561640.0  1.583391e+11  2967867.0
1                            3.0    569499.0  1.481120e+11  2767018.0
2                            1.0    687524.0  1.952329e+11  3629234.0
3                            1.0    744915.0  2.146375e+11  3877042.0
4                            5.0   1088592.0  2.779758e+11  4921872.0
...                          ...         ...           ...        ...
2016                         4.0    223027.0  6.962116e+10   871289.0
2017                         2.0    179239.0  5.412557e+10   677495.0
2018                        10.0    249892.0  8.655212e+10  1078487.0
2019                         4.0    248338.0  8.595351e+10  1064698.0
2020                         1.0    231856.0  7.972573e+10   984898.0

     Объем открытыхпозиций            РазмерыГО(руб./контракт)
                      руб.     контр. РазмерыГО(руб./контракт)
0             1.165832e+11  2169030.0                   5914.0
1             1.038948e+11  1945596.0                   5874.0
2             1.159871e+11  2130862.0                   5988.0
3             1.199455e+11  2134300.0                   6182.0
4             1.126098e+11  1992812.0                   5086.0
...                    ...        ...                      ...
2016          3.213248e+11  4010544.0                  12339.0
2017          3.192193e+11  3991538.0                  12261.0
2018          3.173176e+11  3927198.0                  12377.0
2019          3.136668e+11  3868990.0                  12402.0
2020          3.016621e+11  3723350.0                  12380.0

[2021 rows x 16 columns]

In [219]:
df.to_csv('Si_2015_2023.csv')

### Brent

In [22]:
#вставляем ссылку с нужным инструментом
url = 'https://www.moex.com/ru/forts/contractbaseresults.aspx?base=OG'  #настроим вручную дату

In [23]:
#жмём, откроется гугл бразуер не пугаемся этого и не закрываем его
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(30)

In [24]:
#жмём
driver.get(url)
#после открытия страницы нажимаем в бразуере "Согласен"

In [37]:
df = pd.DataFrame()

In [38]:
#читаем
df = pd.read_html(driver.find_element(By.CLASS_NAME, "tablels").get_attribute('outerHTML'))[0]

In [39]:
df.columns

MultiIndex([(                        'Дата',                         'Дата'),
            (                 'Кодфьючерса',                  'Кодфьючерса'),
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            (                   'Изменение',                    'Изменение'),
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')],
           )

In [41]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
            (                 'Числосделок',                  'Числосделок'),
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: (str(x).replace('\xa0', "")))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Числосделок', 'Числосделок')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [42]:
#чтобы ошибка не вылезала
def tryy(y):
    try:
        y = float(y)
        return(y)
    except:  
        pass

In [43]:
for i in [
            
            ('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот'),
            (               'Расчетнаяцена',                'Расчетнаяцена'),
            (            'Ценапервойсделки',             'Ценапервойсделки'),
            (                 'Максим.цена',                  'Максим.цена'),
            (                  'Миним.цена',                   'Миним.цена'),
            (         'Ценапоследнейсделки',          'Ценапоследнейсделки'),
            
            ( 'Объемпоследнейсделки,контр.',  'Объемпоследнейсделки,контр.'),
           
            (                'Объем торгов',                         'руб.'),
            (                'Объем торгов',                       'контр.'),
            (       'Объем открытыхпозиций',                         'руб.'),
            (       'Объем открытыхпозиций',                       'контр.'),
            (    'РазмерыГО(руб./контракт)',     'РазмерыГО(руб./контракт)')] :
    print(i)
    df[i] = df[i].apply(lambda x: tryy(x))

('Средне-взвешеннаяцена за лот', 'Средне-взвешеннаяцена за лот')
('Расчетнаяцена', 'Расчетнаяцена')
('Ценапервойсделки', 'Ценапервойсделки')
('Максим.цена', 'Максим.цена')
('Миним.цена', 'Миним.цена')
('Ценапоследнейсделки', 'Ценапоследнейсделки')
('Объемпоследнейсделки,контр.', 'Объемпоследнейсделки,контр.')
('Объем торгов', 'руб.')
('Объем торгов', 'контр.')
('Объем открытыхпозиций', 'руб.')
('Объем открытыхпозиций', 'контр.')
('РазмерыГО(руб./контракт)', 'РазмерыГО(руб./контракт)')

In [44]:
df = df[:2021]

In [45]:
df = df.iloc[::-1]

In [46]:
df.reindex(index=df.index[::-1])

            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена  \
            Дата Кодфьючерса Средне-взвешеннаяцена за лот Расчетнаяцена
0     01.06.2015        BRM5                        651.0        6462.0
1     02.06.2015        BRM5                       6516.0        6512.0
2     03.06.2015        BRM5                       6466.0        6421.0
3     04.06.2015        BRM5                       6334.0        6234.0
4     05.06.2015        BRM5                       6194.0        6185.0
...          ...         ...                          ...           ...
2016  25.05.2023        BRM3                       7756.0        7611.0
2017  26.05.2023        BRM3                       7674.0          77.0
2018  29.05.2023        BRM3                       7708.0        7684.0
2019  30.05.2023        BRM3                       7551.0        7413.0
2020  31.05.2023        BRM3                       7293.0        7289.0

     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение  \
     Ценапервойсделки Максим.цена Миним.цена Ценапоследнейсделки Изменение
0              6475.0       658.0     6426.0              6462.0   -0,42 %
1              6462.0      6582.0     6435.0              6512.0   +0,77 %
2              6517.0      6582.0     6378.0               642.0   -1,41 %
3              6416.0      6428.0     6194.0              6234.0   -2,90 %
4               623.0      6285.0     6096.0              6185.0   -0,79 %
...               ...         ...        ...                 ...       ...
2016           7846.0      7883.0     7601.0              7602.0   -3,08 %
2017           7611.0      7749.0     7593.0              7695.0   +1,22 %
2018           7698.0       778.0     7646.0              7685.0   -0,13 %
2019           7691.0      7741.0     7386.0              7411.0   -3,56 %
2020           7408.0      7435.0      716.0               729.0   -1,63 %

     Объемпоследнейсделки,контр. Числосделок  Объем торгов            \
     Объемпоследнейсделки,контр. Числосделок          руб.    контр.
0                            8.0       41807  9.783243e+09  281063.0
1                            1.0       37178  7.128774e+09  205930.0
2                            3.0       41969  9.176525e+09  262600.0
3                            3.0       38663  8.647822e+09  244536.0
4                            1.0       49153  9.989675e+09  285488.0
...                          ...         ...           ...       ...
2016                         1.0       81399  1.673593e+10  268949.0
2017                         3.0       61938  1.181457e+10  192366.0
2018                         9.0       41023  7.684564e+09  123261.0
2019                         1.0       75687  1.418897e+10  231563.0
2020                         1.0       80873  1.502550e+10  253950.0

     Объем открытыхпозиций           РазмерыГО(руб./контракт)
                      руб.    контр. РазмерыГО(руб./контракт)
0             3.208642e+09   92868.0                   5062.0
1             3.388873e+09   97952.0                   5069.0
2             2.680837e+09   77250.0                   5090.0
3             2.410194e+09   69252.0                   5108.0
4             2.222661e+09   63614.0                   4960.0
...                    ...       ...                      ...
2016          1.972137e+10  322954.0                  12730.0
2017          1.767792e+10  286876.0                  12820.0
2018          1.779377e+10  286308.0                  12781.0
2019          1.683678e+10  279882.0                  12417.0
2020          1.400006e+10  236800.0                  12240.0

[2021 rows x 16 columns]

In [47]:
df.to_csv('Br_2015_2023.csv')

### Причешем таблицы

In [61]:
SNGS = pd.read_csv('SNGS_2015_2023.csv')

In [62]:
SNGS = SNGS[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем', 'Срвзв.цена']]

In [63]:
SNGS['Дата торгов'] = pd.to_datetime(SNGS['Дата торгов'], yearfirst = True)

In [64]:
SNGS = SNGS.sort_values('Дата торгов', ascending = False)

In [65]:
SNGS

     Дата торгов Код инструмента  Сделок, шт.        Объем  Срвзв.цена
0     2023-05-31            SNGS         5948  267791369.5      24.350
1     2023-05-30            SNGS        11787  431421745.0      24.475
2     2023-05-29            SNGS        10700  456050798.5      24.600
3     2023-05-26            SNGS         8406  311175353.0      24.275
4     2023-05-25            SNGS         6651  303947047.0      24.200
...          ...             ...          ...          ...         ...
2016  2015-06-05            SNGS        10493  420405100.5      31.745
2017  2015-06-04            SNGS        15270  576908949.5      31.770
2018  2015-06-03            SNGS        17968  773459826.0      31.685
2019  2015-06-02            SNGS        10080  658378287.5      31.925
2020  2015-06-01            SNGS        11065  704175802.5      32.185

[2021 rows x 5 columns]

In [66]:
SNGS.to_csv('SNGS_2015_2023_v2.csv')

In [9]:
SBER = pd.read_csv('SBER_2015_2023.csv')

In [331]:
SBER = SBER[['Дата торгов', 'Код инструмента', 'Сделок, шт.', 'Объем', 'Срвзв.цена']]

In [332]:
SBER['Дата торгов'] = pd.to_datetime(SBER['Дата торгов'], yearfirst = True)

In [340]:
SBER = SBER.sort_values('Дата торгов', ascending = False)

In [343]:
SBER

     Дата торгов Код инструмента  Сделок, шт.         Объем  Срвзв.цена
0     2023-05-31            SBER       180151  1.779406e+10      244.05
1     2023-05-30            SBER       153572  2.068190e+10      247.59
2     2023-05-29            SBER       133878  1.701772e+10      250.27
3     2023-05-26            SBER       150126  1.706429e+10      246.58
4     2023-05-25            SBER       152798  1.734260e+10      244.66
...          ...             ...          ...           ...         ...
2016  2015-06-05            SBER        79355  5.480892e+09       70.92
2017  2015-06-04            SBER       106164  7.845642e+09       71.34
2018  2015-06-03            SBER        96899  7.798511e+09       72.74
2019  2015-06-02            SBER        66811  5.525455e+09       73.29
2020  2015-06-01            SBER        93551  8.321020e+09       73.50

[2021 rows x 5 columns]

In [406]:
SBER.to_csv('SBER_2015_2023_v2.csv')

In [386]:
Si = pd.read_csv('Si_2015_2023.csv')

In [387]:
Si = Si[['Дата', 'Кодфьючерса', 'Средне-взвешеннаяцена за лот',
       'Расчетнаяцена', 'Ценапервойсделки', 'Максим.цена', 'Миним.цена',
       'Ценапоследнейсделки', 'Изменение', 'Объемпоследнейсделки,контр.',
       'Числосделок', 'Объем торгов', 'Объем торгов.1',
       'Объем открытыхпозиций', 'Объем открытыхпозиций.1',
       'РазмерыГО(руб./контракт)']]

In [388]:
Si = Si[1::]

In [389]:
Si.index = np.arange(0, len(Si))

In [390]:
Si['Дата'] = pd.to_datetime(Si['Дата'], dayfirst = True)

In [391]:
Si = Si.sort_values('Дата', ascending = False)

In [394]:
Si

,Дата,Кодфьючерса,Средне-взвешеннаяцена за лот,Расчетнаяцена,Ценапервойсделки,Максим.цена,Миним.цена,Ценапоследнейсделки,Изменение,"Объемпоследнейсделки,контр.",Числосделок,Объем торгов,Объем торгов.1,Объем открытыхпозиций,Объем открытыхпозиций.1,РазмерыГО(руб./контракт)
0,2023-05-31,SiM3,80945.0,81019.0,81062.0,81183.0,80610.0,81039.0,"-0,01 %",1.0,231856.0,79725726278.0,984898.0,301662093650.0,3723350.0,12380.0
1,2023-05-30,SiM3,80730.0,81072.0,80800.0,81323.0,80088.0,81050.0,"+0,29 %",4.0,248338.0,85953509197.0,1064698.0,313666757280.0,3868990.0,12402.0
2,2023-05-29,SiM3,80255.0,80800.0,79933.0,80932.0,79731.0,80815.0,"+1,07 %",10.0,249892.0,86552115292.0,1078487.0,317317598400.0,3927198.0,12377.0
3,2023-05-26,SiM3,79889.0,79974.0,80100.0,80170.0,79581.0,79956.0,"-0,18 %",2.0,179239.0,54125574474.0,677495.0,319219260012.0,3991538.0,12261.0
4,2023-05-25,SiM3,79906.0,80120.0,80027.0,80250.0,79512.0,80101.0,"+0,18 %",4.0,223027.0,69621158492.0,871289.0,321324785280.0,4010544.0,12339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,2015-06-05,SiM5,56478.0,56508.0,56235.0,57390.0,55707.0,56508.0,"+0,55 %",5.0,1088592.0,277975818931.0,4921872.0,112609820496.0,1992812.0,5086.0
2017,2015-06-04,SiM5,55353.0,56199.0,54406.0,56297.0,54363.0,56199.0,"+3,25 %",1.0,744915.0,214637486533.0,3877042.0,119945525700.0,2134300.0,6182.0
2018,2015-06-03,SiM5,53795.0,54432.0,53340.0,54628.0,52935.0,54432.0,"+1,93 %",1.0,687524.0,195232865779.0,3629234.0,115987080384.0,2130862.0,5988.0
2019,2015-06-02,SiM5,53527.0,53400.0,53725.0,54009.0,53226.0,53400.0,"-0,65 %",3.0,569499.0,148111977125.0,2767018.0,103894826400.0,1945596.0,5874.0
2020,2015-06-01,SiM5,53358.0,53749.0,52650.0,53814.0,52561.0,53749.0,"+2,21 %",1.0,561640.0,158339141109.0,2967867.0,116583193470.0,2169030.0,5914.0

In [395]:
Si.to_csv('Si_2015_2023_v2.csv')

In [306]:
Br = pd.read_csv('Br_2015_2023.csv')

In [307]:
Br = Br[['Дата', 'Кодфьючерса', 'Средне-взвешеннаяцена за лот',
       'Расчетнаяцена', 'Ценапервойсделки', 'Максим.цена', 'Миним.цена',
       'Ценапоследнейсделки', 'Изменение', 'Объемпоследнейсделки,контр.',
       'Числосделок', 'Объем торгов', 'Объем торгов.1',
       'Объем открытыхпозиций', 'Объем открытыхпозиций.1',
       'РазмерыГО(руб./контракт)']]

In [308]:
Br = Br[1::]

In [309]:
Br.index = np.arange(0, len(Br))

In [310]:
Br['Дата'] = pd.to_datetime(Br['Дата'], dayfirst = True)

In [311]:
Br = Br.sort_values('Дата', ascending = False)

In [312]:
Br

,Дата,Кодфьючерса,Средне-взвешеннаяцена за лот,Расчетнаяцена,Ценапервойсделки,Максим.цена,Миним.цена,Ценапоследнейсделки,Изменение,"Объемпоследнейсделки,контр.",Числосделок,Объем торгов,Объем торгов.1,Объем открытыхпозиций,Объем открытыхпозиций.1,РазмерыГО(руб./контракт)
0,2023-05-31,BRM3,7293.0,7289.0,7408.0,7435.0,716.0,729.0,"-1,63 %",1.0,80873,15025501387.0,253950.0,14000061184.0,236800.0,12240.0
1,2023-05-30,BRM3,7551.0,7413.0,7691.0,7741.0,7386.0,7411.0,"-3,56 %",1.0,75687,14188970897.0,231563.0,16836783107.0,279882.0,12417.0
2,2023-05-29,BRM3,7708.0,7684.0,7698.0,778.0,7646.0,7685.0,"-0,13 %",9.0,41023,7684564448.0,123261.0,17793767344.0,286308.0,12781.0
3,2023-05-26,BRM3,7674.0,77.0,7611.0,7749.0,7593.0,7695.0,"+1,22 %",3.0,61938,11814574438.0,192366.0,17677924510.0,286876.0,12820.0
4,2023-05-25,BRM3,7756.0,7611.0,7846.0,7883.0,7601.0,7602.0,"-3,08 %",1.0,81399,16735933767.0,268949.0,19721366864.0,322954.0,12730.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,2015-06-05,BRM5,6194.0,6185.0,623.0,6285.0,6096.0,6185.0,"-0,79 %",1.0,49153,9989675405.0,285488.0,2222661073.0,63614.0,4960.0
2017,2015-06-04,BRM5,6334.0,6234.0,6416.0,6428.0,6194.0,6234.0,"-2,90 %",3.0,38663,8647821527.0,244536.0,2410193976.0,69252.0,5108.0
2018,2015-06-03,BRM5,6466.0,6421.0,6517.0,6582.0,6378.0,642.0,"-1,41 %",3.0,41969,9176525070.0,262600.0,2680836878.0,77250.0,5090.0
2019,2015-06-02,BRM5,6516.0,6512.0,6462.0,6582.0,6435.0,6512.0,"+0,77 %",1.0,37178,7128773709.0,205930.0,3388872771.0,97952.0,5069.0
2020,2015-06-01,BRM5,651.0,6462.0,6475.0,658.0,6426.0,6462.0,"-0,42 %",8.0,41807,9783243022.0,281063.0,3208642335.0,92868.0,5062.0

In [ ]:
#не запарсились запятые, исправим это

In [313]:
def tryconvert3(x): #чтобы пропускать ошибки
    try:
        z = str(x)[str(x).find('    ')+1:str(x).find('.0')][:2] + '.' + str(str(x)[str(x).find('    ')+1:str(x).find('.0')])[2:]
        return float(z)
    except:
        pass

In [314]:
def tryconvert4(x): #чтобы пропускать ошибки
    try:
        z = str(x)[str(x).find('    ')+1:str(x).find('.0')][:3] + '.' + str(str(x)[str(x).find('    ')+1:str(x).find('.0')])[3:] 
        return float(z)
    except:
        pass

In [315]:
Br['Средне-взвешеннаяцена за лот'][0:190] = Br['Средне-взвешеннаяцена за лот'][0:190].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/2222743789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][0:190] = Br['Средне-взвешеннаяцена за лот'][0:190].apply(lambda x: tryconvert3(x))

In [316]:
Br['Средне-взвешеннаяцена за лот'][190:195] = Br['Средне-взвешеннаяцена за лот'][190:195].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/618445873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][190:195] = Br['Средне-взвешеннаяцена за лот'][190:195].apply(lambda x: tryconvert4(x))

In [317]:
Br['Средне-взвешеннаяцена за лот'][195:209] = Br['Средне-взвешеннаяцена за лот'][195:209].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/2403272356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][195:209] = Br['Средне-взвешеннаяцена за лот'][195:209].apply(lambda x: tryconvert3(x))

In [318]:
Br['Средне-взвешеннаяцена за лот'][209:223] = Br['Средне-взвешеннаяцена за лот'][209:223].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/610792366.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][209:223] = Br['Средне-взвешеннаяцена за лот'][209:223].apply(lambda x: tryconvert4(x))

In [319]:
Br['Средне-взвешеннаяцена за лот'][223:224] = Br['Средне-взвешеннаяцена за лот'][223:224].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/2441163158.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][223:224] = Br['Средне-взвешеннаяцена за лот'][223:224].apply(lambda x: tryconvert3(x))

In [320]:
Br['Средне-взвешеннаяцена за лот'][224:286] = Br['Средне-взвешеннаяцена за лот'][224:286].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/2056674334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][224:286] = Br['Средне-взвешеннаяцена за лот'][224:286].apply(lambda x: tryconvert4(x))

In [321]:
Br['Средне-взвешеннаяцена за лот'][286:288] = Br['Средне-взвешеннаяцена за лот'][286:288].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/2731235774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][286:288] = Br['Средне-взвешеннаяцена за лот'][286:288].apply(lambda x: tryconvert3(x))

In [322]:
Br['Средне-взвешеннаяцена за лот'][288:303] = Br['Средне-взвешеннаяцена за лот'][288:303].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/283215072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][288:303] = Br['Средне-взвешеннаяцена за лот'][288:303].apply(lambda x: tryconvert4(x))

In [323]:
Br['Средне-взвешеннаяцена за лот'][303:306] = Br['Средне-взвешеннаяцена за лот'][303:306].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/1792627296.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][303:306] = Br['Средне-взвешеннаяцена за лот'][303:306].apply(lambda x: tryconvert3(x))

In [324]:
Br['Средне-взвешеннаяцена за лот'][306:314] = Br['Средне-взвешеннаяцена за лот'][306:314].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/1964672775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][306:314] = Br['Средне-взвешеннаяцена за лот'][306:314].apply(lambda x: tryconvert4(x))

In [325]:
Br['Средне-взвешеннаяцена за лот'][314:315] = Br['Средне-взвешеннаяцена за лот'][314:315].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/733371153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][314:315] = Br['Средне-взвешеннаяцена за лот'][314:315].apply(lambda x: tryconvert3(x))

In [326]:
Br['Средне-взвешеннаяцена за лот'][315:317] = Br['Средне-взвешеннаяцена за лот'][315:317].apply(lambda x: tryconvert4(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/3709238154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][315:317] = Br['Средне-взвешеннаяцена за лот'][315:317].apply(lambda x: tryconvert4(x))

In [327]:
Br['Средне-взвешеннаяцена за лот'][317:] = Br['Средне-взвешеннаяцена за лот'][317:].apply(lambda x: tryconvert3(x))

C:\Users\1678~1\AppData\Local\Temp/ipykernel_1988/896418081.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Br['Средне-взвешеннаяцена за лот'][317:] = Br['Средне-взвешеннаяцена за лот'][317:].apply(lambda x: tryconvert3(x))

In [328]:
Br.to_csv('Br_2015_2023_v2.csv')